cabal-version: 3.0

name:
  faster-richer-tags
version:
  0.1
synopsis:
  Server that looks up haskell entities, similar to tags in editors but more precise
license:
  Apache-2.0
author:
  Sergey Vinokurov
maintainer:
  serg.foo@gmail.com
category:
  Development
build-type:
  Simple

flag dev
  description:
    Enable development aids
  default:
    False
  manual:
    True

common ghc-options
  default-language:
    GHC2021

  default-extensions:
    LambdaCase

  ghc-options:
    -Weverything
    -Wno-all-missed-specialisations
    -Wno-implicit-prelude
    -Wno-missed-specialisations
    -Wno-missing-import-lists
    -Wno-missing-local-signatures
    -Wno-safe
    -Wno-unsafe
    -Wno-unused-packages

    -Wno-redundant-constraints

    -Werror
    -Wwarn=unused-packages

  if impl(ghc >= 8.8)
    ghc-options:
      -Wno-missing-deriving-strategies

  if impl(ghc >= 8.10)
    ghc-options:
      -Wno-missing-safe-haskell-mode
      -- -Wno-prepositive-qualified-module

  if impl(ghc >= 9.2)
    ghc-options:
      -Wno-missing-kind-signatures

  if impl(ghc >= 9.8)
    ghc-options:
      -Wno-missing-role-annotations
      -Wno-missing-poly-kind-signatures

library
  import: ghc-options
  if flag(dev)
    cpp-options: -DDEVELOPMENT
  if os(windows)
    build-depends: unix-compat
  else
    build-depends: unix >= 2.6

  mixins:
    fast-tags hiding ( System.OsPath.Ext )

  build-depends:
    , abstract-par
    , array
    , attoparsec >= 0.13.1.0
    , base >= 4
    , bimap
    , bytestring
    , conduit
    , conduit-extra
    , containers
    , deepseq
    , directory
    , dlist
    , emacs-native
    , exceptions >= 0.8
    , fast-tags >= 1.3
    , filepath
    , hashable
    , lifted-async
    , microlens
    , monad-control >= 1.0
    , mtl >= 2.2
    , network >= 2.6
    , parallel
    , pointed
    , prettyprinter
    , prettyprinter-combinators
    , profunctors >= 5.2
    , regex-tdfa >= 1.2.2
    , scientific
    , sexp-grammar
    , stm
    , stm-chans
    , store
    , streaming-commons
    , text
    , transformers
    , transformers-base
    , unsafe
    , utf8-string >= 0.3
  exposed-modules:
    Control.Monad.Ext
    Control.Monad.ErrorExcept
    Control.Monad.Except.Ext
    Control.Monad.Filesystem
    Control.Monad.Logging
    Control.Monad.Logging.Simple
    Control.Monad.Par.Combinator.Ext
    Control.Parallel.Strategies.Ext

    Data.CompiledRegex
    Data.Condition
    Data.ErrorMessage
    Data.Foldable.Ext
    Data.HasLens
    Data.IgnoreEqOrdHashNFData
    Data.KeyMap
    Data.Map.NonEmpty
    Data.MonoidalMap
    Data.Path
    Data.Promise
    Data.SizedList
    Data.SubkeyMap
    Data.SymbolMap
    Data.Symbols
    Data.Symbols.MacroName

    FasterRicherTags.Types

    GHC.Stack.Ext

    Haskell.Language.Blocks

    Haskell.Language.LexerSimple.LensBlaze
    Haskell.Language.LexerSimple.Lexer
    Haskell.Language.LexerSimple.Types

    Haskell.Language.Lexer
    Haskell.Language.Lexer.CppTypes
    Haskell.Language.Lexer.Types
    Haskell.Language.Preprocessor.ResolvePreprocessor

    Haskell.Language.Lexer.Env
    Haskell.Language.Lexer.InputStack
    Haskell.Language.Lexer.Input
    Haskell.Language.Lexer.Lexer
    Haskell.Language.Lexer.Monad
    Haskell.Language.Lexer.Preprocessor
    Haskell.Language.Lexer.RulePredicate
    Haskell.Language.Lexer.State

    Haskell.Language.Server.Sexp
    Haskell.Language.Server.Tags
    Haskell.Language.Server.Tags.AnalyzeHeader
    Haskell.Language.Server.Tags.LoadFiles
    Haskell.Language.Server.Tags.Search
    Haskell.Language.Server.Tags.SearchM
    Haskell.Language.Server.Tags.Types
    Haskell.Language.Server.Tags.Types.Imports
    Haskell.Language.Server.Tags.Types.Modules

    Prettyprinter.Ext

    -- Interface for tests
    Haskell.Language.Server.Tags.LoadModule
  other-modules:
    Control.Monad.EitherCPS

    Data.Filesystem
    Data.NBSem
    Data.Path.Internal
    Data.Strict.Pair
  hs-source-dirs:
    src
  build-tool-depends:
    alex:alex >= 3.1.7

executable faster-richer-tags
  import: ghc-options
  main-is:
    exe/FasterRicherTagsMain.hs
  other-modules:
    FasterRicherTags.CompactFormat
  hs-source-dirs:
    .
    exe
  build-depends:
    , base >= 4.16
    , bytestring
    , containers
    , directory
    , directory-ospath-streaming
    , emacs-native
    , file-io
    , filepath >= 1.4.100
    , ghc-prim
    , mtl
    , optparse-applicative
    , prettyprinter
    , prettyprinter-combinators
    , text
    , faster-richer-tags
  ghc-options:
    -rtsopts
    -- -threaded
    -- "-with-rtsopts=-N -A32M"
    -main-is FasterRicherTagsMain

executable haskell-tags-server
  import: ghc-options
  if !os(windows)
    build-depends: unix >= 2.6
  main-is:
    exe/HaskellTagsServerMain.hs
  build-depends:
    , base
    , containers
    , directory
    , faster-richer-tags
    , network
    , optparse-applicative
  ghc-options:
    -rtsopts
    -threaded
    "-with-rtsopts=-N"
    -main-is HaskellTagsServerMain

test-suite test-faster-richer-tags
  import: ghc-options
  if !os(windows)
    build-depends: unix >= 2.6
  type:
    exitcode-stdio-1.0
  hs-source-dirs:
    tests
  main-is:
    Main.hs
  other-modules:
    Control.Monad.Logging.DiscardLogs
    Data.GenericDiff
    Data.Map.NonEmpty.Tests
    Haskell.Language.Lexer.Preprocessor.Tests
    Haskell.Language.Lexer.Tests
    Haskell.Language.Lexer.Tokenisation
    Haskell.Language.Lexer.TokenisationUtils
    Haskell.Language.Server.Tags.AnalyzeHeaderTests
    Haskell.Language.Server.Tags.AnalyzeHeaderTests.Regressions
    Haskell.Language.Server.Tags.TypesTests
    Haskell.Language.ModuleTests
    PortPool
    ServerTests
    ServerTests.Data
    ServerTests.LogCollectingServer
    TestUtils
  build-depends:
    , QuickCheck
    -- For MultilineStrings, GHC >= 9.12
    , base >= 4.21
    , bytestring
    , containers
    , deepseq
    , dlist
    , exceptions
    , fast-tags
    , faster-richer-tags
    , filepath >= 1.5
    , monad-control
    , mtl
    , network
    , prettyprinter
    , prettyprinter-combinators
    , scientific
    , sexp-grammar
    , tasty >= 0.7
    , tasty-hunit >= 0.4
    , tasty-quickcheck
    , text
    , transformers
    , transformers-base
  ghc-options:
    -rtsopts
    -threaded
    "-with-rtsopts=-A32m -N"
