# For more information, see: http://docs.haskellstack.org/en/stable/yaml_configuration.html

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-8.9
# resolver: lts-6.23
# resolver: ghc-7.10.3

# Local packages, usually specified by relative directory name
packages:
- '.'
- location: /home/sergey/projects/haskell/projects/dev-tools/fast-tags/
  extra-dep: true
- location: /home/sergey/projects/haskell/projects/thirdparty/bert/
  extra-dep: true

# # Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
# extra-deps:
# # - bert-1.2.2.5
# - alex-3.2.1

# - fast-tags-1.2
